In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error
from sklearn import metrics
from io import StringIO
import os
import warnings
warnings.filterwarnings('ignore')

#Importing data from csv and read Training Dataset

input_dir = 'C:/Users/MMohan/Videos/Scikit-Learn_ML/Models_MM/ST-RF_ILs/'
df_train = pd.read_csv(input_dir + 'SurfaceTension-ILs.csv')
var_columns = [c for c in df_train.columns if c not in('IonicLiuid','ST-exp')]
X = df_train.loc[:, var_columns]
y = df_train.loc[:, 'ST-exp']

# Splitting the data into Training and Testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.45, random_state=15)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

X_test.describe()

,T (K),S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13,Area (Å2),Mol-Wt (g/mol)
count,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.00000
mean,320.524798,0.298268,2.402158,7.184934,10.124776,3.854881,0.338764,0.385521,1.880012,4.411077,2.675563,2.796820,1.593855,0.674040,378.727617,323.76485
std,28.558183,0.766066,1.321442,1.803826,6.820732,4.341646,0.941318,0.701082,3.434408,4.764366,2.881959,2.328475,1.695692,1.092297,132.639948,137.43637
min,263.730000,0.000000,0.115350,2.314200,0.842450,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,144.378700,77.08280
25%,303.150000,0.010700,2.114950,6.686200,6.460950,1.436100,0.000000,0.000000,0.218250,1.080400,0.790650,0.669300,0.031000,0.000000,300.464900,226.31650
50%,318.125000,0.138500,2.498200,6.703950,8.584450,2.647400,0.030200,0.147550,1.615700,2.681900,1.778650,1.833000,1.639200,0.000000,346.018100,273.33000
75%,333.150000,0.151400,2.545750,7.541750,10.591050,4.234000,0.336000,0.279738,2.390250,9.532000,2.920550,5.229700,2.835950,1.409000,416.618300,421.28080
max,532.600000,6.741000,16.289000,21.695000,36.754500,21.261350,8.835000,5.466000,50.957000,39.610000,12.220500,7.247200,8.993000,8.993000,1061.395600,928.86880

In [19]:
# creating a regression model with Training and Testing sets
MLR_model = LinearRegression()

# fitting the model
MLR_model.fit(X_train, y_train)

# Make prediction for Training
pred_train = MLR_model.predict(X_train)

# Mean absolute error (MAE)
mae_train = mean_absolute_error(y_train.values.ravel(), pred_train)
# Mean squared error (MSE)
mse_train = mean_squared_error(y_train.values.ravel(), pred_train)
rmse_train = (mse_train**0.5)
# R-squared scores
r2_train = r2_score(y_train.values.ravel(), pred_train)

# Print metrics
print("")
print('MAE_Training:', round(mae_train, 3))
print('MSE_Training:', round(mse_train, 3))
print('RMSE_Training:', round(rmse_train, 3))
print('R2_Training:', round(r2_train, 3))

# Make prediction for Testing
pred_test = MLR_model.predict(X_test)

# Mean absolute error (MAE)
mae_test = mean_absolute_error(y_test.values.ravel(), pred_test)
# Mean squared error (MSE)
mse_test = mean_squared_error(y_test.values.ravel(), pred_test)
rmse_test = (mse_test**0.5)
# R-squared scores
r2_test = r2_score(y_test.values.ravel(), pred_test)

# Print metrics
print("")
print('MAE_Testing:', round(mae_test, 3))
print('MSE_Testing:', round(mse_test, 4))
print('RMSE_Testing:', round(rmse_test, 4))
print('R2_Testing:', round(r2_test, 3))

MAE_Training: 5.028
MSE_Training: 42.448
RMSE_Training: 6.515
R2_Training: 0.478

MAE_Testing: 4.962
MSE_Testing: 40.6429
RMSE_Testing: 6.3752
R2_Testing: 0.474

In [20]:
# creating a regression model
MLR_model = LinearRegression()

# fitting the model
MLR_model.fit(X_train, y_train)

# with statsmodels Training
import statsmodels.api as sm
X_train = sm.add_constant(X_train) # adding a constant
 
model_train = sm.OLS(y_train, X_train).fit()
predictions_train = model_train.predict(X_train) 

print_MLRmodel_train = model_train.summary()
print("")
print("************************** Training **************************")
print("")
print(print_MLRmodel_train)

************************** Training **************************

                            OLS Regression Results
==============================================================================
Dep. Variable:                 ST-exp   R-squared:                       0.478
Model:                            OLS   Adj. R-squared:                  0.472
Method:                 Least Squares   F-statistic:                     78.45
Date:                Fri, 03 Mar 2023   Prob (F-statistic):          2.59e-180
Time:                        13:55:54   Log-Likelihood:                -4570.8
No. Observations:                1388   AIC:                             9176.
Df Residuals:                    1371   BIC:                             9265.
Df Model:                          16
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const             63.7548      6.254     10.194      0.000      51.486      76.023
T (K)             -0.0787      0.007    -11.513      0.000      -0.092      -0.065
S1                -1.6592      0.391     -4.240      0.000      -2.427      -0.892
S2                 0.8702      0.240      3.620      0.000       0.399       1.342
S3                 0.4316      0.192      2.251      0.025       0.055       0.808
S4                -0.0163      0.171     -0.096      0.924      -0.352       0.319
S5                -0.2352      0.267     -0.882      0.378      -0.758       0.288
S6                -0.0485      0.500     -0.097      0.923      -1.030       0.933
S7                 0.6865      0.613      1.120      0.263      -0.516       1.889
S8                -0.5048      0.283     -1.786      0.074      -1.059       0.050
S9                 0.1443      0.127      1.133      0.257      -0.106       0.394
S10                0.8612      0.239      3.607      0.000       0.393       1.330
S11                0.6438      0.407      1.583      0.114      -0.154       1.441
S12                1.9696      0.635      3.102      0.002       0.724       3.215
S13                0.7903      0.929      0.851      0.395      -1.031       2.612
Area (Å2)         -0.0106      0.013     -0.789      0.431      -0.037       0.016
Mol-Wt (g/mol)    -0.0218      0.008     -2.895      0.004      -0.037      -0.007
==============================================================================
Omnibus:                       69.424   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               92.366
Skew:                           0.471   Prob(JB):                     8.77e-21
Kurtosis:                       3.843   Cond. No.                     2.23e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.23e+04. This might indicate that there are
strong multicollinearity or other numerical problems.